# spigotngrok
# 

FROM felixklauke/paperspigot:1.15.2

USER root

RUN mkdir /opt/ngrok
ADD ngrok /opt/ngrok
ADD minecraft_url.py /opt/ngrok
RUN chown -R minecraft:minecraft /opt/ngrok

USER minecraft
